In [174]:
from math import sqrt

import math
import numpy as np

Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [175]:
np.arange(1, 11, 1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [176]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [177]:
np.random.default_rng().integers(high=10, low=1, size=(5, 5))

array([[5, 7, 9, 9, 9],
       [5, 5, 4, 4, 9],
       [6, 2, 5, 8, 3],
       [2, 8, 5, 9, 6],
       [4, 1, 2, 8, 4]])

Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [178]:
np.random.default_rng().random((4, 4))

array([[0.53989119, 0.84296837, 0.67807446, 0.36677589],
       [0.7963829 , 0.55411359, 0.65959228, 0.58315523],
       [0.14025342, 0.14469959, 0.82015931, 0.27864734],
       [0.75020767, 0.92482661, 0.14019153, 0.3992957 ]])

Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [206]:
array_1  = np.random.default_rng().integers(high=10, low=1, size=(5,))
array_2 = np.random.default_rng().integers(high=10, low=1, size=(5,))

array_1 * array_2


array([12, 28, 45,  7, 36])

Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [183]:
vector_1 = np.random.default_rng().random((7,))
vector_2 = np.random.default_rng().random((7,))

np.dot(vector_1, vector_2)

np.float64(0.8775746056047031)

Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [184]:
matrix_1 = np.random.default_rng().uniform(high=10, low=1, size=(2,2))
matrix_2 = np.random.default_rng().uniform(high=10, low=1, size=(2,3))

matrix_1 @ matrix_2

array([[85.79648496, 31.35275672, 59.22091174],
       [67.78578014, 32.22851951, 46.48046737]])

Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [185]:
matrix = np.random.default_rng().integers(high=10, low=1, size=(3,3))
np.linalg.inv(matrix)

array([[-0.19587629,  0.17525773,  0.05154639],
       [ 0.21649485, -0.29896907,  0.20618557],
       [ 0.1443299 ,  0.13402062, -0.19587629]])

Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [186]:
matrix = np.random.default_rng().integers(high=10, low=1, size=(4,4))
matrix.T

array([[5, 1, 7, 9],
       [9, 4, 3, 9],
       [1, 5, 1, 1],
       [4, 8, 5, 7]])

Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [187]:
matrix = np.random.default_rng().uniform(high=10, low=1, size=(3,4))
vector = np.random.default_rng().uniform(high=10, low=1, size=(3,))

vector @ matrix

array([104.50098602,  48.15320542,  88.69036382, 103.56333484])

Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [188]:
matrix = np.random.default_rng().uniform(high=10, low=1, size=(2,3))
vector = np.random.default_rng().uniform(high=10, low=1, size=(3,))

matrix @ vector

array([129.00950923, 171.02763697])

Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [189]:
matrix_1 = np.random.default_rng().uniform(high=10, low=1, size=(2,2))
matrix_2 = np.random.default_rng().uniform(high=10, low=1, size=(2,2))

matrix_1 * matrix_2

array([[22.52221265, 85.12794158],
       [59.09134016, 41.33071754]])

Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [190]:
matrix_1 = np.random.default_rng().uniform(high=10, low=1, size=(2,2))
matrix_2 = np.random.default_rng().uniform(high=10, low=1, size=(2,2))
matrix_1 @ matrix_2

array([[ 86.59483688,  84.8580557 ],
       [144.71051375, 142.47272233]])

Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [191]:
matrix = np.random.default_rng().integers(high=100, low=1, size=(5,5))
matrix.sum()

np.int64(1401)

Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [192]:
matrix_1 = np.random.default_rng().integers(high=10, low=1, size=(4,4))
matrix_2 = np.random.default_rng().integers(high=10, low=1, size=(4,4))

matrix_1 - matrix_2

array([[ 6, -1,  2, -2],
       [ 6,  0, -1, -2],
       [ 0,  2, -7,  6],
       [-6,  2, -4, -6]])

Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [193]:
matrix = np.random.default_rng().random(size=(3,3))
np.sum(matrix, axis=1)

array([1.44988988, 1.2742637 , 1.85402089])

Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.


In [194]:
matrix = np.random.default_rng().integers(low=1, high=100, size=(3,4))
matrix ** 2

array([[9604, 6241, 5776,    1],
       [1849, 1225, 6241, 1849],
       [3136, 8281, 5929,  361]])

Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [195]:
matrix = np.random.default_rng().integers(low=1, high=50, size=(4,))
matrix ** 0.5

array([3.31662479, 5.09901951, 3.        , 3.16227766])

Замініть усі непарні числа в arr на -1

In [209]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.vectorize(lambda n: n if n % 2 == 0 else -1)(arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Створіть та перетворіть 1D-масив на 2D-масив із 2 рядками.

In [197]:
arr = np.random.default_rng().integers(low=1, high=10, size=(10,))
arr.reshape((2, len(arr) // 2))

array([[5, 4, 1, 5, 2],
       [7, 5, 2, 6, 6]])


Створіть два двовимірні масиви `a` і `b`, та складіть масиви вертикально.

In [198]:
a = np.random.default_rng().integers(low=1, high=10, size=(2,5))
b = np.random.default_rng().integers(low=1, high=10, size=(2,5))

np.append(a, b, axis=0)

array([[9, 6, 4, 9, 5],
       [4, 3, 7, 5, 6],
       [9, 2, 7, 5, 6],
       [5, 7, 5, 5, 8]])

Створіть наступний шаблон без жорсткого кодування (Hard coding). Використовуйте лише функції NumPy і наведений нижче масив введення.

Input:

`a = np.array([1, 2, 3])`

Output:

`array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`

In [216]:
a = np.array([1, 2, 3])

part_1 = np.append([], [
    np.repeat(n, a.size)
    for n in a
])
part_2 = np.tile(a, a.size)


np.append(part_1, part_2)

array([1., 1., 1., 2., 2., 2., 3., 3., 3., 1., 2., 3., 1., 2., 3., 1., 2.,
       3.])

Отримайте спільні елементи між `a` і `b`.

`a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])`

`b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])`

In [200]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

np.intersect1d(a, b)

array([2, 4])

Отримайте позиції перших 5 максимальних значень у заданому масиві `a`.

`np.random.seed(100)`

`a = np.random.uniform(1, 50, 20)`

In [201]:
np.random.seed(100)
a = np.random.uniform(1, 50, 20)
np.sort(a)[::-1][:5]

array([48.95256545, 44.67477576, 42.39403048, 41.466785  , 40.99501269])


Вилучіть усі значення `NaN` із одновимірного масиву.

`a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])`

In [227]:
a = np.array([1, 2, 3, np.nan, 5, 6, 7, np.nan])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])


Обчисліть евклідову відстань між двома масивами `a` і `b`.

`a = np.array([1, 2, 3, 4, 5])`

`b = np.array([4, 5, 6, 7, 8])`

In [234]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])

np.sqrt(np.sum((a - b) ** 2))

np.float64(6.708203932499369)


Знайдіть індекс 5-го повторення числа `1` у масиві `x`.

`x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])`

In [239]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
np.where(x == 1)[0][4]

np.int64(8)


Знайдіть повторювані записи від 2-го випадку повторення і далі у заданому масиві і позначте їх як `True`. Перше повторення має бути `False`.

Input:

`np.random.seed(100)`

`a = np.random.randint(0, 5, 10)`

`[0 0 3 0 2 4 2 2 2 2]`

Output:

`[False True False True False False True True True True]`


In [205]:
np.random.seed(100)
a = np.random.randint(0, 5, 10)
occurrences = []
result = []

for number in a:
    if number in occurrences:
        result.append(True)
    else:
        occurrences.append(number)
        result.append(False)

result

[False, True, False, True, False, False, True, True, True, True]